name: publish

on: [ push ]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build
        run: |
          docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images-samples/helloworld:latest .

      - name: Push
        run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images-samples/helloworld:latest

      - name: Deploy
        run: |
          gcloud run deploy helloworld \
          --region us-east1 \
          --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images-samples/helloworld \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}